repos:
  - repo: local
    hooks:
      - id: spotless-check
        name: Spotless Check (Java Style Format)
        entry: ./gradlew spotlessCheck
        language: system
        files: \.java$
        pass_filenames: false