CREATE TABLE IF NOT EXISTS accounts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	account_number VARCHAR(255) NOT NULL,
	version BIGINT,
	constraint UK_accounts_account_number unique (account_number)
) ;

CREATE TABLE IF NOT EXISTS ledger_entries (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	account_number VARCHAR(255) NOT NULL,
	direction VARCHAR(255) NOT NULL CHECK (direction IN ('DEBIT','CREDIT')),
	amount NUMERIC(38,2) NOT NULL,
	transaction_id VARCHAR(255) NOT NULL,
	occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
) ;

CREATE INDEX IF NOT EXISTS idx_demo_ledger_account_occurred ON ledger_entries (account_number, occurred_at);

CREATE TABLE IF NOT EXISTS eod_snapshots (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	account_number VARCHAR(255) NOT NULL,
	closing_balance NUMERIC(38,2) NOT NULL,
	interest_amount NUMERIC(38,2) NOT NULL,
	settlement_date DATE NOT NULL,
	computed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
	constraint uk_demo_eod_snapshot_account_date unique (account_number, settlement_date)
) ;

CREATE TABLE IF NOT EXISTS reconciliation_discrepancies (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	account_number VARCHAR(255) NOT NULL,
	settlement_date DATE NOT NULL,
	expected_balance NUMERIC(38,2),
	actual_balance NUMERIC(38,2),
	status VARCHAR(255) NOT NULL CHECK (status IN ('MISMATCH','NO_SNAPSHOT')),
	computed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
	constraint uk_demo_reconciliation_discrepancy_account_date unique (account_number, settlement_date)
) ;

CREATE TABLE IF NOT EXISTS outbox_event (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	aggregate_type VARCHAR(100) NOT NULL,
	aggregate_id VARCHAR(100) NOT NULL,
	event_type VARCHAR(100) NOT NULL,
	payload TEXT NOT NULL,
	created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
	previous_hash VARCHAR(64) NOT NULL,
	entry_hash VARCHAR(64) NOT NULL,
	trace_id VARCHAR(32),
	span_id VARCHAR(16),
	constraint uk_demo_outbox_event_entry_hash unique (entry_hash)
) ;

CREATE TABLE IF NOT EXISTS outbox_chain_tail (
	id BIGINT PRIMARY KEY,
	latest_entry_hash VARCHAR(64) NOT NULL
) ;
