CREATE TABLE IF NOT EXISTS accounts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	account_number VARCHAR(255) NOT NULL,
	version BIGINT,
	constraint UK_accounts_account_number unique (account_number)
) ;

CREATE TABLE IF NOT EXISTS ledger_entries (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	account_number VARCHAR(255) NOT NULL,
	direction VARCHAR(255) NOT NULL CHECK (direction IN ('DEBIT','CREDIT')),
	amount NUMERIC(38,2) NOT NULL,
	transaction_id VARCHAR(255) NOT NULL,
	occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
) ;

CREATE INDEX IF NOT EXISTS idx_demo_ledger_account_occurred ON ledger_entries (account_number, occurred_at);

CREATE TABLE IF NOT EXISTS eod_snapshots (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	account_number VARCHAR(255) NOT NULL,
	closing_balance NUMERIC(38,2) NOT NULL,
	interest_amount NUMERIC(38,2) NOT NULL,
	settlement_date DATE NOT NULL,
	computed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
	constraint uk_demo_eod_snapshot_account_date unique (account_number, settlement_date)
) ;
