CREATE TABLE IF NOT EXISTS accounts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	account_number VARCHAR(255) NOT NULL,
	version BIGINT,
	constraint UK_accounts_account_number unique (account_number)
) ;
