spring:
  application:
    name: fbrl-backend

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fbrl_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: fbrl_user
    password: fbrlpassword
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true

logging:
  level:
    root: WARN
    com.fbrl: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.orm.session: ERROR
    org.springframework: WARN

outbox:
  polling:
    fixed-delay-ms : 3000
    batch-size: 100